service: hopebytheroadside
runtime: php81
env: standard

default_expiration: "5m"

handlers:

# Robots
- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots\.txt
  secure: always


# Static resources folder
- url: /static
  static_dir: public/static
  secure: always
  expiration: "1h"
- url: /media
  static_dir: public/media
  secure: always
  expiration: "14d"
- url: /carousel
  static_dir: public/carousel
  secure: always
  expiration: "14d"


# Root of folder
- url: .*
  script: auto
  secure: always

entrypoint:
  serve index.php
